spring.application.name=bridge-dds
server.port=9015


# Log pattern configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Log levels
logging.level.root=INFO
logging.level.com.webber=DEBUG
logging.level.org.springframework=INFO
logging.level.jakarta.mail=INFO

# File configuration
logging.file.name=/var/log/bridge-dds/application.log

# Rolling policy
logging.logback.rollingpolicy.file-name-pattern=/var/log/bridge-dds/application.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=3GB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.clean-history-on-start=false



